import type { Quiz } from "./quiz-types";
import { attachmentProfiles, bigFiveProfiles, careProfiles, discProfiles, enneagramProfiles, sixteenTypeProfiles } from "./framework-profiles";

export const quizzes: Quiz[] = [
  {
    slug: "jungian-16-type", title: "Jungian 16-Type Explorer", kicker: "Classic framework",
    description: "Explore the four-letter pattern behind types such as INFJ, ENFP, ISTJ, and ENTJ.",
    time: "7 min", icon: "16", accent: "plum", scoring: "four-letter",
    dimensions: [["E", "I"], ["S", "N"], ["T", "F"], ["J", "P"]],
    questions: [
      { prompt: "After a demanding week, what restores you more?", options: [{ label: "Sharing energy with people or activity", value: "E" }, { label: "Quiet time with very little input", value: "I" }] },
      { prompt: "In a new group, you are more likely to…", options: [{ label: "Think out loud and connect as you go", value: "E" }, { label: "Observe first and join when ready", value: "I" }] },
      { prompt: "When something exciting happens, you usually…", options: [{ label: "Share it right away", value: "E" }, { label: "Hold it close until you process it", value: "I" }] },
      { prompt: "When learning something new, you trust…", options: [{ label: "Concrete examples and proven details", value: "S" }, { label: "Patterns, possibilities, and the big picture", value: "N" }] },
      { prompt: "You notice first…", options: [{ label: "What is actually happening", value: "S" }, { label: "What it might mean or become", value: "N" }] },
      { prompt: "A useful explanation is…", options: [{ label: "Specific and practical", value: "S" }, { label: "Conceptual and imaginative", value: "N" }] },
      { prompt: "In a difficult decision, your first filter is…", options: [{ label: "What is logical and consistent", value: "T" }, { label: "What honors the people and values involved", value: "F" }] },
      { prompt: "Feedback feels fairest when it is…", options: [{ label: "Direct, accurate, and impersonal", value: "T" }, { label: "Honest and attentive to emotional impact", value: "F" }] },
      { prompt: "During disagreement, you naturally defend…", options: [{ label: "The clearest reasoning", value: "T" }, { label: "The human context", value: "F" }] },
      { prompt: "Your ideal weekend is…", options: [{ label: "Planned enough to know what is happening", value: "J" }, { label: "Open enough to follow the moment", value: "P" }] },
      { prompt: "A looming deadline makes you…", options: [{ label: "Want to finish and close the loop", value: "J" }, { label: "Stay flexible until direction is clear", value: "P" }] },
      { prompt: "Plans feel best when they are…", options: [{ label: "Decided and dependable", value: "J" }, { label: "Adaptable and easy to change", value: "P" }] },
    ],
    profiles: sixteenTypeProfiles,
  },
  {
    slug: "disc-style", title: "DISC-Style Behavior Profile", kicker: "Classic framework",
    description: "See whether your behavior leans toward D, I, S, or C—and what your partner should know.",
    time: "6 min", icon: "D", accent: "rose",
    questions: [
      { prompt: "When a group is stuck, you usually…", options: [{ label: "Make a decision and move", value: "D" }, { label: "Lift the energy and rally people", value: "I" }, { label: "Listen and build agreement", value: "S" }, { label: "Check the facts and risks", value: "C" }] },
      { prompt: "Others are most likely to call you…", options: [{ label: "Direct", value: "D" }, { label: "Expressive", value: "I" }, { label: "Patient", value: "S" }, { label: "Precise", value: "C" }] },
      { prompt: "Under pressure, your strength is…", options: [{ label: "Taking charge", value: "D" }, { label: "Keeping hope alive", value: "I" }, { label: "Staying steady", value: "S" }, { label: "Preventing mistakes", value: "C" }] },
      { prompt: "A frustrating environment has too much…", options: [{ label: "Delay", value: "D" }, { label: "Isolation", value: "I" }, { label: "Sudden change", value: "S" }, { label: "Sloppiness", value: "C" }] },
      { prompt: "When making plans together, you prefer…", options: [{ label: "A clear goal and fast decisions", value: "D" }, { label: "Excitement and room for people", value: "I" }, { label: "A pace everyone can handle", value: "S" }, { label: "Enough detail to feel confident", value: "C" }] },
      { prompt: "Your communication is naturally…", options: [{ label: "Brief and outcome-focused", value: "D" }, { label: "Animated and story-filled", value: "I" }, { label: "Warm and considerate", value: "S" }, { label: "Careful and evidence-based", value: "C" }] },
      { prompt: "You feel respected when someone…", options: [{ label: "Trusts your capability", value: "D" }, { label: "Responds with enthusiasm", value: "I" }, { label: "Shows loyalty and patience", value: "S" }, { label: "Comes prepared", value: "C" }] },
      { prompt: "Your growth edge is often…", options: [{ label: "Slowing down for people", value: "D" }, { label: "Following through on details", value: "I" }, { label: "Speaking up sooner", value: "S" }, { label: "Acting before everything is certain", value: "C" }] },
    ],
    profiles: discProfiles,
  },
  {
    slug: "big-five", title: "Big Five Personality Snapshot", kicker: "Research-based framework",
    description: "Explore your strongest current tendency across the five broad personality dimensions.",
    time: "6 min", icon: "5", accent: "blue",
    questions: [
      { prompt: "Which quality feels most like your strength?", options: [{ label: "Curiosity and imagination", value: "O" }, { label: "Reliability and self-discipline", value: "C" }, { label: "Energy and social confidence", value: "E" }, { label: "Kindness and cooperation", value: "A" }, { label: "Awareness of risk and emotion", value: "N" }] },
      { prompt: "In a shared home, you tend to…", options: [{ label: "Reinvent how things could work", value: "O" }, { label: "Create routines and finish tasks", value: "C" }, { label: "Keep the atmosphere lively", value: "E" }, { label: "Notice whether everyone is comfortable", value: "A" }, { label: "Spot tension early", value: "N" }] },
      { prompt: "Your mind naturally asks…", options: [{ label: "What else is possible?", value: "O" }, { label: "What needs to be done?", value: "C" }, { label: "Who can I share this with?", value: "E" }, { label: "How will this affect people?", value: "A" }, { label: "What could go wrong?", value: "N" }] },
      { prompt: "Friends often rely on you for…", options: [{ label: "A fresh perspective", value: "O" }, { label: "Follow-through", value: "C" }, { label: "Momentum", value: "E" }, { label: "Understanding", value: "A" }, { label: "Emotional awareness", value: "N" }] },
      { prompt: "When plans change, your asset is…", options: [{ label: "Finding an interesting alternative", value: "O" }, { label: "Rebuilding the plan", value: "C" }, { label: "Keeping the mood up", value: "E" }, { label: "Helping everyone adjust", value: "A" }, { label: "Preparing for the impact", value: "N" }] },
      { prompt: "Which compliment lands deepest?", options: [{ label: "You make me think differently.", value: "O" }, { label: "I can count on you.", value: "C" }, { label: "You bring life into the room.", value: "E" }, { label: "You make people feel safe.", value: "A" }, { label: "You understand the emotional stakes.", value: "N" }] },
      { prompt: "In conflict, you contribute by…", options: [{ label: "Reframing the problem", value: "O" }, { label: "Keeping to facts and next steps", value: "C" }, { label: "Talking openly", value: "E" }, { label: "Finding common ground", value: "A" }, { label: "Naming the worry beneath it", value: "N" }] },
      { prompt: "Your ideal growth goal is to…", options: [{ label: "Explore more deeply", value: "O" }, { label: "Become more consistent", value: "C" }, { label: "Express yourself more boldly", value: "E" }, { label: "Balance kindness with boundaries", value: "A" }, { label: "Feel steadier under uncertainty", value: "N" }] },
    ],
    profiles: bigFiveProfiles,
  },
  {
    slug: "enneagram", title: "Enneagram Motivation Explorer", kicker: "Classic framework",
    description: "Reflect on the deeper need that may organize your habits, fears, and way of relating.",
    time: "8 min", icon: "9", accent: "amber",
    questions: [
      { prompt: "At your best, what do you most want to contribute?", options: [{ label: "Integrity and improvement", value: "1" }, { label: "Care and support", value: "2" }, { label: "Excellence and momentum", value: "3" }] },
      { prompt: "Which inner pull feels strongest?", options: [{ label: "To be authentic and understood", value: "4" }, { label: "To understand and preserve energy", value: "5" }, { label: "To be safe and prepared", value: "6" }] },
      { prompt: "Which freedom matters most?", options: [{ label: "Freedom to explore what is exciting", value: "7" }, { label: "Freedom from being controlled", value: "8" }, { label: "Freedom from conflict and pressure", value: "9" }] },
      { prompt: "Under strain, you tend to…", options: [{ label: "Become critical and tense", value: "1" }, { label: "Over-help and hope to be needed", value: "2" }, { label: "Work harder and hide vulnerability", value: "3" }] },
      { prompt: "A painful misunderstanding would be…", options: [{ label: "You are too much or do not belong", value: "4" }, { label: "You are incapable or uninformed", value: "5" }, { label: "You cannot trust your support system", value: "6" }] },
      { prompt: "When discomfort arrives, you may…", options: [{ label: "Reach for a brighter option", value: "7" }, { label: "Meet it with force and control", value: "8" }, { label: "Go numb and postpone action", value: "9" }] },
      { prompt: "Which reassurance lands deepest?", options: [{ label: "You are good even when imperfect.", value: "1" }, { label: "You are loved even when not helping.", value: "2" }, { label: "You matter even when not achieving.", value: "3" }] },
      { prompt: "Which reassurance lands deepest?", options: [{ label: "Your feelings make sense and you belong.", value: "4" }, { label: "You have enough space and capability.", value: "5" }, { label: "You are supported and can trust yourself.", value: "6" }] },
      { prompt: "Which reassurance lands deepest?", options: [{ label: "You will not be trapped in pain.", value: "7" }, { label: "You can be soft without losing strength.", value: "8" }, { label: "Your presence and priorities matter.", value: "9" }] },
    ],
    profiles: enneagramProfiles,
  },
  {
    slug: "attachment-tendencies", title: "Attachment Tendencies", kicker: "Relationship framework",
    description: "Reflect on how you seek closeness, protection, and repair when a relationship feels uncertain.",
    time: "6 min", icon: "⌁", accent: "sage",
    questions: [
      { prompt: "When someone important feels distant, you…", options: [{ label: "Ask directly and stay grounded", value: "secure" }, { label: "Seek reassurance quickly", value: "anxious" }, { label: "Pull back and rely on yourself", value: "avoidant" }, { label: "Want closeness but feel wary", value: "fearful" }] },
      { prompt: "During conflict, your system wants…", options: [{ label: "A fair conversation and repair", value: "secure" }, { label: "Proof the bond is okay", value: "anxious" }, { label: "Space and fewer demands", value: "avoidant" }, { label: "Connection and escape at once", value: "fearful" }] },
      { prompt: "Depending on a partner feels…", options: [{ label: "Natural when support goes both ways", value: "secure" }, { label: "Necessary but sometimes frightening", value: "anxious" }, { label: "Risky; independence feels safer", value: "avoidant" }, { label: "Appealing and dangerous", value: "fearful" }] },
      { prompt: "If a message goes unanswered, you think…", options: [{ label: "They are probably busy", value: "secure" }, { label: "Something is wrong between us", value: "anxious" }, { label: "Good—I have space", value: "avoidant" }, { label: "I should not care, but I do", value: "fearful" }] },
      { prompt: "The hardest thing to ask for is…", options: [{ label: "I can usually name what I need", value: "secure" }, { label: "Space without fearing disconnection", value: "anxious" }, { label: "Comfort and emotional support", value: "avoidant" }, { label: "Anything that makes me vulnerable", value: "fearful" }] },
      { prompt: "After a loving moment, you feel…", options: [{ label: "Warm and settled", value: "secure" }, { label: "Relieved, then alert for change", value: "anxious" }, { label: "Good, but ready to regain space", value: "avoidant" }, { label: "Moved and a little exposed", value: "fearful" }] },
      { prompt: "A caring partner can help by…", options: [{ label: "Being honest, warm, and consistent", value: "secure" }, { label: "Offering reassurance and follow-through", value: "anxious" }, { label: "Respecting autonomy without going cold", value: "avoidant" }, { label: "Moving slowly and proving safety", value: "fearful" }] },
      { prompt: "Your growth edge is…", options: [{ label: "Keeping healthy patterns under stress", value: "secure" }, { label: "Self-soothing before seeking certainty", value: "anxious" }, { label: "Staying present when closeness rises", value: "avoidant" }, { label: "Trusting safe connection in small steps", value: "fearful" }] },
    ],
    profiles: attachmentProfiles,
  },
  {
    slug: "care-language", title: "How I Feel Cared For", kicker: "Relationship framework",
    description: "Discover whether presence, reassurance, or thoughtful action lands most deeply for you.",
    time: "4 min", icon: "♡", accent: "coral",
    questions: [
      { prompt: "After a hard day, what would feel best?", options: [{ label: "A long hug and quiet closeness", value: "presence" }, { label: "Hearing why I am appreciated", value: "words" }, { label: "Someone taking one thing off my plate", value: "actions" }] },
      { prompt: "The most meaningful surprise would be…", options: [{ label: "An evening with no distractions", value: "presence" }, { label: "A heartfelt note I can keep", value: "words" }, { label: "A task thoughtfully handled", value: "actions" }] },
      { prompt: "When we reconnect, I want…", options: [{ label: "Undivided attention", value: "presence" }, { label: "Warm, specific reassurance", value: "words" }, { label: "A gesture that shows you remembered", value: "actions" }] },
      { prompt: "I feel overlooked when…", options: [{ label: "We are together but distracted", value: "presence" }, { label: "Affection is assumed but not said", value: "words" }, { label: "I carry everything alone", value: "actions" }] },
      { prompt: "Pick the sentence that feels most loving.", options: [{ label: "I put my phone away—I’m all yours.", value: "presence" }, { label: "I see you, and I admire you.", value: "words" }, { label: "I handled it so you can breathe.", value: "actions" }] },
    ],
    profiles: careProfiles,
  },
];
